### PR TITLE
Feat/enable expressing overlap distance in step

### PR DESCRIPTION
**Pull request by AmauryLiet**
This new props allows simplifying the API from:
```
        allowOverlap={false}
        min={min}
        max={max}
        minMarkerOverlapDistance={
          (MIN_RANGE_LENGTH * sliderLength) / (max - min)
        }
```
to
```
        allowOverlap={false}
        min={min}
        max={max}
        minMarkerOverlapDistance={MIN_RANGE_LENGTH}
```
saving the implementer the need to recompute `stepLength` which is already used internally by the lib.

My guess being that this unit (step instead of pixels), is present more frequently in real-world use cases

### CODE REVIEW

**Comment by ptomasroos** [comment]
This is nice! But also a breaking change. But again I have no idea how many people who are using just this particular feature :)

**Comment by AmauryLiet** [comment]
@ptomasroos it shouldn't be a breaking change as I kept the existing prop unchanged ;)

**Comment by AmauryLiet** [comment]
happy to get your feedback if you have a better naming by the way

**Comment by ptomasroos** [comment]
Thanks! Missed that. Looks great, again thanks for the contribution!

**Comment by AmauryLiet** [comment]
No worries, thanks for the super quick review and merge 💪

**Pull request merged**
