### PR TITLE
Add prop minMarkerOverlapDistance to allow setting a custom value for how close two markers can get to each other

### LINKED ISSUE #63: Markers override each other
Hello.
first, thanks for the very useful library.
I have a little problem: when the markers are too close it overrides each other
screenshot from 2018-03-11 10-44-36
Do you have any solution? thanks.

### PR DESCRIPTION
**Pull request by dyihoon90**
Fixes #63 

This prop will allow users of the library to define a distance between the two markers that is greater than the default step length. It can be used to ensure the rendered markers won't overlap each other.

Without minMarkerOverlapDistance:
image

Setting minMarkerOverlapDistance to the slider marker's size means user cannot slide the markers closer than this defined distance.
In this image, minMarkerOverlapDistance is set to the marker size:
image

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks @dyihoon90 this looks like a great addition!

**Comment by dyihoon90** [comment]
Thanks for your kind words @ptomasroos , and thanks to you guys for open-sourcing this awesome library! 👍 
It really helped my team a lot :)

**Comment by ptomasroos** [comment]
Can we add a example to the examples/Basic perhaps to show the usage?

**Comment by dyihoon90** [comment]
yes of course

**Comment by dyihoon90** [comment]
Hi @ptomasroos, I have added an example in examples/Basic

**Comment by ptomasroos** [comment]
Thanks a lot!

**Pull request merged**
