### PR TITLE
Fix #45

### LINKED ISSUE #45: Markers
Which property would I call in order to change the style of the markers?

Currently the markers go over the side of the line and I am trying to get the edge of the marker to touch the edge of the line.

This is what it looks like in case my description wasn't helpful:
https://imgur.com/a/GKp2y

The top image is what I want, the bottom image is what is currently happening.

### PR DESCRIPTION
**Pull request by raynor85**
Supplying 'markerSize' as prop allow the component to know how to position the markers on the edges without overflowing. It also solves an issue on Android in which it is impossible to drag the marker from the overflowing part (when they are positioned either at the very beginning or at the very end of the slider).

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks! This looks promising. Has it been tested on iOS as well?

**Comment by raynor85** [comment]
Yes it has been. The only problem with it is, without snapping, you can
always pull the markers’ external half outside the track, but at least the
values are calculated within and snapping seems to be working as it should

**Comment by raynor85** [comment]
@ptomasroos I have updated the PR with a proper fix that works for any value of snapped prop. I think the only thing missing is updating the documentation. If you are keen to merge it, I will be happy to add it as well. Let me know, I think this is a must-have feature

**Comment by ptomasroos** [comment]
Thanks for your work on this! LGTM

**Comment by raynor85** [comment]
We need to update the documentation... do you want me to do that?

**Comment by raynor85** [comment]
And you also need to publish it on npm :)

**Comment by ptomasroos** [comment]
Yes but I prefer the documentation to be in place before publishing!

Please feel free to update the docs

**Comment by raynor85** [comment]
Ok PR ready https://github.com/ptomasroos/react-native-multi-slider/pull/200

Please let me know when it is ready in npm.js :)

Ruben

**Comment by YeshanJay-Urban** [comment]
Any idea on when a version would be published to npm (with this fix)?

**Comment by ptomasroos** [comment]
Can you send a pr @YeshanJay-Urban ?

**Comment by raynor85** [comment]
The fix has already been merged, you just need to publish it to npm. @YeshanJay-Urban alternatively you can just include in your package.json the github code rather than npm:

`"@ptomasroos/react-native-multi-slider": "ptomasroos/react-native-multi-slider"`

**Pull request merged**
