### PR TITLE
Fix valueToPosition converter

### LINKED ISSUE #49: Marker position is shifted for Snapped
When you enable `snapped`, marker is shifted by one value to the right.
It's not noticeable for high values, but totally not usable when you set max to low value e.g. `max={4}`. 

This is `<MultiSlider min={1} max={4} values={[1, 2]} />` but it shows 2 and 3 position.
screen shot 2018-01-04 at 8 56 54 am

There is incorrectly calculated index in `converters.js`.
I will send PR right away.

### PR DESCRIPTION
**Pull request by jakubzaba**
Fix index calculation to convert value to position correctly.

Closes #49

### CODE REVIEW

**Comment by ptomasroos** [comment]
You wrote this @sibelius, it was in order to fix overlapping? Can't remember. Can you please take a look

**Comment by sibelius** [comment]
this `closest` function is not so good, but using `indexOf` will cause some troubles as well

this will happen if the `valuesArray` does not contain will value

we should implement a better `closest` function

in rambda is something like this

```jsx
const getClosest = curry((counts, goal) => {
  return counts
    .reduce((prev, curr) => Math.abs(curr - goal) < Math.abs(prev - goal) ? curr : prev);
});

const closestTo5 = getClosest(_, 5);
const closestTo = getClosest([4, 9, 15, 6, 2]);
```

**Comment by jakubzaba** [comment]
Ok then, I returned `closest` back and found simple solution for this issue.

**Comment by sibelius** [comment]
can you test if this function works for you?

```jsx
const closest = (array, n) => array.reduce((prev, curr) => Math.abs(curr - goal) < Math.abs(prev - goal) ? curr : prev)
```

**Comment by jakubzaba** [comment]
It's not necessary to implement `closest` so complicated. It is useful for unsorted array of numbers. `valuesArray` is sorted, so simple comparison `<=` is good enough.

**Comment by ptomasroos** [comment]
This looks good to me! Do you agree @sibelius ? I think most arrays vill be sorted its a fair assumption that its monotonically increasing

**Comment by sibelius** [comment]
good enough for me

**Comment by ptomasroos** [comment]
Thanks for the efforts!

**Comment by mrtnzlml** [comment]
Could you please tag and release a new version of this library (with this fix)? 🙂

**Comment by ptomasroos** [comment]
@mrtnzlml will do later this week! Sorry for being a bit slow, hadn't had the chance to test it fully in our app hence the delay in order to not cause regressions!

**Pull request merged**
