### PR TITLE
Added support for RN<=0.44 (View.propTypes)

### PR DESCRIPTION
**Pull request by PeterBLITZ**

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thank you very much!
Looks good!

**Comment by PeterBLITZ** [comment]
Hi! When to expect a merge?
I have checked this patch on the old RN 0.43 and the new RN 0.47. All works fine.

**Comment by ptomasroos** [comment]
Thanks for the contribution!

**Comment by PeterBLITZ** [comment]
I'm sorry, but can you bump version and push to NPM registry? :)

**Comment by ptomasroos** [comment]
Done as we speak @PeterBLITZ 
Have a great day

**Comment by peteychuk** [comment]
Well done!

**Pull request merged**
