### PR TITLE
Remove duplicate track.

### LINKED ISSUE #135: Track bug
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [ ] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

Hi, I am using latest version from github repository. When i running example i get it https://monosnap.com/file/pFmIl4yUBBQvMtLszi4d6IxzByO129

### PR DESCRIPTION
**Pull request by robwalkerco**
This PR removes a duplicate track that was causing #135.

Closes #135

### CODE REVIEW

**Comment by robwalkerco** [comment]
FYI.

The removed code was added in #120 - https://github.com/ptomasroos/react-native-multi-slider/commit/660455a8411f4a03b1dfa1dbb53447488f10db52#diff-2d0b63ae56a87a9fe627226866a8e83fR415

**Comment by FrikkieSnyman** [comment]
Yes @robwalkerco! Discussed this here: https://github.com/ptomasroos/react-native-multi-slider/issues/128

i think neither @ptomasroos or I have had time to look at it, so awesome that you did!

**Comment by ptomasroos** [comment]
Awesome! Thanks!

**Comment by ptomasroos** [comment]
Thank you @robwalkerco 
Will release a update in the coming days to npm

**Pull request merged**
