### PR TITLE
Fix values change finish

### PR DESCRIPTION
**Pull request by FrikkieSnyman**
@ptomasroos I think this is correct. However, now if the code using this lib doesn't update the passed props from the callback, it will run into the same problem.

TBH, I don't think this flow is correct, as there is now a very tight coupling between the props and the state of the component.

### CODE REVIEW

**Comment by FrikkieSnyman** [comment]
Closed because of bad merging

**Comment by ptomasroos** [comment]
Right. I see your point in the case regarding the state.
But in this case of this component, state is kept locally plus we allow props to control the behaviour.
Which is indeed problematic in react terms.

We could rewrite it to require a controlled parent but that again would require quite some changes.

The alternative is to skip updates in the props if it has already been mounted.
And then require the user to actually set a new key on the <MultiSlider when it need to force an update.

Then we wouldn't really have this problem again

**Comment by FrikkieSnyman** [comment]
https://github.com/ptomasroos/react-native-multi-slider/pull/161

**Comment by FrikkieSnyman** [comment]
Agreed. For now, let's merge #161 and then we can revisit this problem later on. 

I think it's also good if we can add this caveat as a note to the readme.md

**Pull request closed without merging**
