### PR TITLE
Allow Slider To be enabled/disabled through props

### PR DESCRIPTION
**Pull request by joshjconlin**

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks. This looks great. I will review during the day !

**Comment by joshjconlin** [comment]
would you be opposed to me doing a large refactor and expansion on this project? i have some pretty cool ideas such as making it work on react web as well as react native and adding support for more features? anything in particular you would like to see if i do this?

**Comment by ptomasroos** [comment]
Feel free. I'm always open to ideas!

**Comment by ptomasroos** [comment]
Thanks! This looks all good to me!

**Comment by BaderSerhan** [comment]
Hello. I don't know why but markerStyle is not working when I disable the marker. Any help?

**Pull request merged**
