### PR TITLE
Feature - Adding step labeling

### PR DESCRIPTION
**Pull request by gusolsso**
* Added so its possible to show steps 
  - Show step labels
  - Show step marks on the track
  - Customizable step labels, prefix and suffix styling etc.
  - Customizable styling for step container, step label and step markers
* Added smooth-snapped
* Added docs

Issue #149 

Reference image:
Skärmavbild 2020-11-12 kl  10 17 31

### CODE REVIEW

**Comment by ptomasroos** [comment]
Really sweet contribution!

**Comment by KyleAsaff** [comment]
can we get this merged? really need this in my project 🙏

**Comment by GedalyaKrycer** [comment]
@ptomasroos could this be added to the NPM package as well? 😄  🙏  Thanks!

**Comment by ptomasroos** [comment]
Yeah I haven't the opportunity to test it currently but I can publish it as a beta if that helps you out. I'm a fraid to break existing packages, that's why I haven't published a new version in a while since one has stepped up to help out testing master before releasing it

**Comment by GedalyaKrycer** [comment]
Gotcha, no worries! What is needed to test the master? (I am just starting out with React Native, so not sure if I can yet be of help. But maybe can work towards being able to test it in the near future.)

**Comment by darkbasic** [comment]
@ptomasroos yes please release a new beta, that would be much appreciated (I have to maintain my own fork since more than one year because the currently released version does not carry the commits I need).

**Comment by Haider-Ali-7** [comment]
> gusolsso

Hi, can we return step label as value instead of returning index?
If i provide steplabel like "One", "Two, and when select the value then it should return "One" or "Two". Is it possible?

**Comment by sania232** [comment]
Can someone please tell me how to add this to my code? The documentation doesn't say anything

**Pull request merged**
