### PR TITLE
Add touch support on selected track

### PR DESCRIPTION
**Pull request by FrikkieSnyman**
Make the markers move when gesturing on the selected track

### CODE REVIEW

**Comment by ptomasroos** [comment]
This is great! Will merge during next week when I've tried it out

**Comment by FrikkieSnyman** [comment]
Hi @ptomasroos! Any updates on this?

**Comment by ptomasroos** [comment]
Thanks for the ping! Last week went to fast, will give it a try during this! \o/

**Comment by FrikkieSnyman** [comment]
Bump again! 😉

**Comment by rafaismyname** [comment]
@ptomasroos could you give this a review?
Awesome contribution!

**Comment by ptomasroos** [comment]
Can we rebase so I can merge this?

**Comment by FrikkieSnyman** [comment]
Pending to confirm whether all went fine here, I was not done with solving the merge conflicts 🙈

**Pull request merged**
