### PR TITLE
update Basic example to RN v0.60

### PR DESCRIPTION
**Pull request by sytolk**
Basic example project works with v.1.0.0 
TODO with v. 2.0.0 from master branch its have this exception. (its needs to check last commits and this properties -> left: NaN)
viber_image_2019-12-12_10-05-25

### CODE REVIEW

**Comment by sytolk** [comment]
This works:
```
"dependencies": {
    "react-native-multi-slider": "git://github.com/ptomasroos/react-native-multi-slider.git#23ca9bf83b5d88b6c6a30523da782122a5fbf857"
  }
```
It appears that this commit breaks RN 60 support:
https://github.com/ptomasroos/react-native-multi-slider/commit/410221bd455783922ed150b9386cbfd41880e869

**Comment by mitaxe** [comment]
@sytolk 
Hey. Is it a fix for `componentWillMount` and `componentWillReceiveProps` deprecated methods?

I see that you attached issue #138, but I used this - 

```
"dependencies": {
    "react-native-multi-slider": "git://github.com/ptomasroos/react-native-multi-slider.git#23ca9bf83b5d88b6c6a30523da782122a5fbf857"
  }
```

and still have the issue.

**Comment by sytolk** [comment]
No this is not a fix for `componentWillMount` and `componentWillReceiveProps` deprecated methods. This update RN to v0.60 in Basic example only. @mitaxe feels free to provide PR for deprecated methods :)

**Comment by mitaxe** [comment]
https://github.com/ptomasroos/react-native-multi-slider/pull/155

**Comment by ptomasroos** [comment]
Superseeded by #158

**Pull request closed without merging**
