### PR TITLE
add RTL support

### PR DESCRIPTION
**Pull request by iamsoorena**
this will make the slider work in RTL apps too.

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks!

**Comment by ptomasroos** [comment]
Any rush in getting it released? Otherwise I'll do it next week.

Thanks for the contribution @iamsoorena

**Comment by iamsoorena** [comment]
Thank you @ptomasroos . There is no rush I'm currently using my own fork in production.

**Comment by iamsoorena** [comment]
@ptomasroos when I read your comment(before edit), you said that it's better to use `const` and I used that. If you think it's better to revert it back to `var` let me know.

**Pull request merged**
