### PR TITLE
Dynamic Label

### PR DESCRIPTION
**Pull request by olahat90**
Dynamic label

screen

### CODE REVIEW

**Comment by ptomasroos** [comment]
Nice! 🎉

**Comment by tn12787** [comment]
Will this be merged?

**Comment by ptomasroos** [comment]
Thanks alot for the PR! Yes I will just try it out and merge during next week!

**Comment by jesouhaite08** [comment]
Any update on this? I'd like to use it, thanks :)

**Comment by rafaismyname** [comment]
@ptomasroos could this one get merged too?

i see that there are lots of awesome pull requests pending review/merge for quite a long time now.
if you need help reviewing/approving them, let me know!

**Pull request merged**
