### PR TITLE
Update example to 0.61.5

### PR DESCRIPTION
**Pull request by baconcheese113**
I realize this seems like a big PR, but it's mostly due to removing the `.lock` files. The main change is just getting the example project to support the latest RN version and switching it to use functional components/hooks.

I've also removed some unused Jest dependencies since this project doesn't currently implement any Jest testing. Also fixed a bug that would be encountered with the DefaultLabel whenever only one slider is used.

### CODE REVIEW

**Comment by baconcheese113** [comment]
Currently working on improving the label in the example 
image

**Comment by baconcheese113** [comment]
Okay, happy with where it's at. Should work as a good showcase for how to create custom high-quality labels. 
image

**Comment by baconcheese113** [comment]
Awaiting your review now :)

Following semver, I've bumped it from 2.0.0 to 2.1.0 since functionality was added, but there shouldn't be any breaking changes.

- `oneMarkerPressed` and `twoMarkerPressed` booleans will now be passed in to the customLabel
- `DefaultLabel` will now be centered horizontally on the slider marker
- `DefaultLabel` won't crash if only one slider is used
- Unused style props in `DefaultLabel` removed
- `DefaultLabel` height adjusted
- `DefaultLabel` shows a selection border while the user is pressing the associated marker now

**Comment by ptomasroos** [comment]
This is a great PR. Will check it out during tomorrow to make sure everything is running fine!

Thanks for putting time into it!

**Comment by baconcheese113** [comment]
Awesome! I realize there are several other PRs to merge as well. If you'd like some help clearing up the backlog and addressing issues I'd love to help, just need collaborator permissions.

**Comment by ptomasroos** [comment]
Again this is great that you took the time to update this.
Metro config works fine without the need of installing and keeping the main repo up to date.

The labels looks really funky on ios, thats the only nit there is and it think we should resolve that before moving on

**Comment by ptomasroos** [comment]
Screenshot 2020-02-04 at 09 07 11
Screenshot 2020-02-04 at 09 06 02
Screenshot 2020-02-04 at 09 05 13
Screenshot 2020-02-04 at 09 05 09

**Comment by baconcheese113** [comment]
Sure can, hadn't touched the iOS side of it yet. Kinda wanted to make sure everything else was okay first. I'll get something in later today 👍 

Do you prefer the generated pod files in source control or not?

**Comment by ptomasroos** [comment]
No need to check in the pod files for the example project IMHO

**Comment by baconcheese113** [comment]
Okay, ready for merge now. As a side note, it's still on 1.0.0 in npm.

The bullet points I listed before should still cover the changes in 2.1.0 pretty well if you don't mind adding it as a `Release` in github.

Also, how would you feel if I made my example slider label the default one instead?

**Comment by ptomasroos** [comment]
Yeah I was thinking that we should rename it now when we're about to release the new update.

Under react-native-range the reason is as I've discussed before in #59 
But I wasn't able to get the other npm package's name with the owners since they didnt want to hand it over.

I think its a good idea to move on with that now and deprecate the prefixed package so its future proof and doesn't become a problem a head for end users

**Comment by sytolk** [comment]
@baconcheese113 I see that you load `react-native-multi-slider` lib in Basic example from `metro.config.js` but this Readme is missing in Example project: https://github.com/sytolk/react-native-multi-slider/blob/cb7f1f0750343e35af6a59e9e3170987da986e88/examples/Basic/README.md
Can you add it? Thanks!

**Comment by ptomasroos** [comment]
I will add it, thanks for the point @sytolk

**Pull request merged**
