### PR TITLE
add types

### PR DESCRIPTION
**Pull request by FrikkieSnyman**
Not sure if it covers all the types, but it's a copy from the typings project that exist for this project

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks whats the reason for putting the types into the source project instead of DefinitelyTyped? Does it make Versioning easier?

**Comment by FrikkieSnyman** [comment]
Yes! Also no need to install multiple packages, and it's easier to keep the types up to dae

**Comment by ptomasroos** [comment]
Can we resolve the conflicts and I will merge this!
Pretty sure we should add enableLabel as well to the type def

**Comment by FrikkieSnyman** [comment]
Done!

**Pull request merged**
