### PR TITLE
Add support for ImageBackground

### PR DESCRIPTION
**Pull request by FrikkieSnyman**
Adds the possibility to pass in a `backgroundImageSource` prop. This is useful when more complex background styles are required (such as a gradient or striped background)

### CODE REVIEW

**Comment by rafaismyname** [comment]
@ptomasroos could this one get merged too?

**Comment by ptomasroos** [comment]
Can you rebase this and I will merge it right away!

**Comment by GedalyaKrycer** [comment]
@FrikkieSnyman or @ptomasroos — Thank you for this update! To clarify, to use this does one simply add in the path to the image as a string and/or import it as a variable? I tried both, but nothing showed up. 

Example of how I set it up on the <MultiSlider /> component. 

`backgroundImageSource={'../../assets/images/workout_feedback/progress-bar-gradient.svg'}`

**Comment by rafaismyname** [comment]
> @FrikkieSnyman or @ptomasroos — Thank you for this update! To clarify, to use this does one simply add in the path to the image as a string and/or import it as a variable? I tried both, but nothing showed up.
> 
> Example of how I set it up on the component.
> 
> `backgroundImageSource={'../../assets/images/workout_feedback/progress-bar-gradient.svg'}`

@GedalyaKrycer the `backgroundImageSource` prop should work just like RN Image's `source` prop: https://reactnative.dev/docs/image#source

**Comment by GedalyaKrycer** [comment]
@rafaismyname thank you, that did the trick!

**Comment by ptomasroos** [comment]
Nice.

Should we add something in the read me or in the Example/ ?

**Comment by FrikkieSnyman** [comment]
@echenran yes, it shows up behind the slider, and can be used as the track. See screenshot attached of what this looks like for how I'm using it in the app that we're building.

WhatsApp Image 2024-01-29 at 10 46 45

>  If so, is there some way to use an image for the selected part of the track?
I'm not aware of this functionality, but that said, I haven't looked at this repo again since I've made this contribution, so I don't know if it's been added. 

But I'm sure @ptomasroos will appreciate if you made a PR with that functionality!

**Pull request merged**
