### PR TITLE
Vertically centered slider

### PR DESCRIPTION
**Pull request by mrxrinc**
The slider itSelf needs to be centered in vertical direction.

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks! Will review soon

**Comment by Kif11** [comment]
This is good fix. Why it isn't merged?

**Comment by ptomasroos** [comment]
I forgot to test it @Kif11 nothing else than that.

**Comment by ptomasroos** [comment]
Published as 1.0.0 at npm, thanks for the PR @mrxrinc

**Pull request merged**
